# Generated by Django 2.2.4 on 2019-08-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoPdelta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('l', models.DecimalField(decimal_places=2, max_digits=5)),
                ('p', models.DecimalField(decimal_places=2, max_digits=5)),
                ('m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('h', models.DecimalField(decimal_places=2, max_digits=5)),
                ('q', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ei', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
